### ISSUE TITLE
n_generate cannot be longer than context

### ISSUE THREAD

**Issue by Gutianpei** [SqueezeBits/QUICK#4]
From the code `examples/benchmark.py` it looks like n_generate stands for the new tokens generated, however when I tried to set n_generate < context I'll get a shape mismatch error:
```
File "/root/QUICK/quick/awq/modules/fused/attn.py", line 48, in reshape_for_broadcast
    assert freqs_cis.shape == (x.shape[1], x.shape[-1])
AssertionError
```
Is there a way to avoid the unnecessarily compute if we have a really long input tokens but only would like to get a short response?

To reproduce, just set
`{"context": 1024, "n_generate": 32},` in L153

**Comment by JHLEE17** [comment]
Thank you for your patience and interest.

We are utilizing code based on the [AutoAWQ](https://github.com/casper-hansen/AutoAWQ/tree/main) framework, and we've incorporated the benchmark code from that project. Upon reviewing your issue, it seems that the problem arises due to the code setting max_new_tokens=n_generate in [here](https://github.com/SqueezeBits/QUICK/blob/6029de92caf6d611d720b9866be7e6a2f47940fb/examples/benchmark.py#L103). This differs from the [original code](https://github.com/casper-hansen/AutoAWQ/blob/68c727a1a338a1e8d988e8f6094e0d38040e0bb6/examples/benchmark.py#L101) where 'max_new_tokens' was replaced by 'max_seq_len'. (because we haven't updated the new AutoAWQ version yet)

We acknowledge the inconvenience this has caused and appreciate your detailed feedback. For now, the decode speed is determined by 'decode_tokens_per_second', so the benchmark results may not significantly differ regardless of 'n_generate'. However, we will work to address this issue promptly with update AutoAWQ version.
